// StudyLoad Tracker: local-first dashboard logic. All personal logs stay in this browser.
const KEYS = { logs: 'studyload-logs-v1', insights: 'studyload-insights-v1' };
let logs = read(KEYS.logs), insights = read(KEYS.insights), editId = null, chartDays = 14;
const $ = (id) => document.getElementById(id);
function read(key) { try { return JSON.parse(localStorage.getItem(key)) || []; } catch { return []; } }
function save(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function isoToday() { return new Date().toISOString().slice(0, 10); }
function dateLabel(date) { return new Date(date + 'T12:00:00').toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }); }
function escapeHTML(value = '') { const div = document.createElement('div'); div.textContent = value; return div.innerHTML; }
function sortedLogs() { return [...logs].sort((a,b) => b.date.localeCompare(a.date)); }
function weekLogs() { const now = new Date(); const monday = new Date(now); monday.setHours(0,0,0,0); monday.setDate(now.getDate() - ((now.getDay() + 6) % 7)); return logs.filter(x => new Date(x.date + 'T12:00:00') >= monday); }
function streak() { const dates = new Set(logs.map(x => x.date)); let d = new Date(); d.setHours(0,0,0,0); if (!dates.has(d.toISOString().slice(0,10))) d.setDate(d.getDate() - 1); let total = 0; while (dates.has(d.toISOString().slice(0,10))) { total++; d.setDate(d.getDate()-1); } return total; }
function renderMetrics() { const latest = sortedLogs()[0], week = weekLogs(), hours = week.reduce((sum,x) => sum + Number(x.hours),0); $('streak').textContent = streak(); $('weekHours').textContent = hours.toFixed(1); $('lastStress').textContent = latest ? latest.stress : '—'; $('averageHours').textContent = week.length ? `${(hours/week.length).toFixed(1)}h` : '0.0h'; $('averageStress').textContent = week.length ? (week.reduce((s,x)=>s+Number(x.stress),0)/week.length).toFixed(1) : '—'; $('weekDays').textContent = week.length; }
function renderHistory() { const oldest = $('sortSelect').value === 'oldest'; const list = sortedLogs(); if (oldest) list.reverse(); $('historyEmpty').classList.toggle('hidden', list.length > 0); $('historyTable').classList.toggle('hidden', !list.length); $('historyBody').innerHTML = list.map(x => `<tr><td>${dateLabel(x.date)}</td><td>${x.subjects.map(s=>`<span class="tag">${escapeHTML(s)}</span>`).join('')}</td><td>${Number(x.hours).toFixed(2)}h</td><td>${x.stress}/5</td><td>${escapeHTML(x.note || '—')}</td><td class="actions-cell"><button class="icon-button" data-edit="${x.id}">Edit</button><button class="icon-button delete" data-delete="${x.id}">Delete</button></td></tr>`).join(''); }
function recent() { return [...logs].sort((a,b)=>a.date.localeCompare(b.date)).slice(-chartDays); }
function emptyChart(message) { return `<div class="no-chart">${message}</div>`; }
function chart(type) { const data = recent(); if (!data.length) return emptyChart('Your trendline will appear after your first check-in.'); const values = data.map(x=>Number(x[type])); const width=400, height=180, top=14, bottom=34, left=9, right=9, max= type==='stress' ? 5 : Math.max(1, ...values), min= type==='stress' ? 1 : 0, range=max-min || 1, inner=height-top-bottom, pointX=i=>left+(i*(width-left-right)/Math.max(1,data.length-1)), pointY=v=>top+(max-v)*inner/range;
 let svg = `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${type} over time"><line class="grid-line" x1="${left}" x2="${width-right}" y1="${top}" y2="${top}"/><line class="grid-line" x1="${left}" x2="${width-right}" y1="${top+inner/2}" y2="${top+inner/2}"/><line class="grid-line" x1="${left}" x2="${width-right}" y1="${top+inner}" y2="${top+inner}"/>`;
 if(type==='stress'){ svg += `<text class="axis-label" x="0" y="${top+3}">5</text><text class="axis-label" x="0" y="${top+inner+3}">1</text>`; const points=values.map((v,i)=>`${pointX(i)},${pointY(v)}`).join(' '); svg+=`<polyline class="line-path" points="${points}"/>${values.map((v,i)=>`<circle class="chart-dot" cx="${pointX(i)}" cy="${pointY(v)}" r="3"/>`).join('')}` } else { const gap=5, barW=Math.max(5,(width-left-right)/data.length-gap); svg+=values.map((v,i)=>`<rect class="bar" x="${pointX(i)-barW/2}" y="${pointY(v)}" width="${barW}" height="${top+inner-pointY(v)}" rx="2"/>`).join('') }
 const labels = data.map((x,i)=> (i===0 || i===data.length-1 || (data.length>8 && i===Math.floor(data.length/2))) ? `<text class="axis-label" x="${pointX(i)}" y="${height-9}" text-anchor="middle">${new Date(x.date+'T12:00').toLocaleDateString(undefined,{month:'numeric',day:'numeric'})}</text>`:'').join(''); return svg+labels+'</svg>'; }
function renderSubjects() { const counts={}; logs.forEach(x=>x.subjects.forEach(s=>counts[s]=(counts[s]||0)+1)); const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5); $('subjectBreakdown').innerHTML=top.length ? top.map(([name,count])=>`<div class="subject-row"><div class="subject-label"><span>${escapeHTML(name)}</span><span>${count} ${count===1?'day':'days'}</span></div><div class="subject-bar"><i style="width:${(count/top[0][1])*100}%"></i></div></div>`).join('') : '<div class="no-chart">Topics you log most often will show here.</div>'; }
function renderInsight() { const item=insights[0]; $('insightEmpty').classList.toggle('hidden', !!item); $('insightContent').classList.toggle('hidden', !item); if(item) $('insightContent').innerHTML=insightMarkup(item); $('insightButton').disabled = logs.length < 2; }
function insightMarkup(item) { const cls=item.risk_level.toLowerCase(); return `<div class="insight-result"><span class="risk ${cls}">${item.risk_level} RISK</span><p>${escapeHTML(item.reasoning)}</p><ul>${item.suggestions.map(s=>`<li>${escapeHTML(s)}</li>`).join('')}</ul></div>`; }
function renderInsightHistory() { $('insightHistory').innerHTML = insights.length ? insights.map(i=>`<article class="card insight-item"><time>${dateLabel(i.createdAt.slice(0,10))}</time><br><span class="risk ${i.risk_level.toLowerCase()}">${i.risk_level} RISK</span><p>${escapeHTML(i.reasoning)}</p></article>`).join('') : '<div class="card empty"><p>Past AI pattern checks will be saved here for comparison.</p></div>'; }
function render() { renderMetrics(); renderHistory(); $('stressChart').innerHTML=chart('stress'); $('hoursChart').innerHTML=chart('hours'); renderSubjects(); renderInsight(); renderInsightHistory(); }
function resetForm() { editId=null; $('logForm').reset(); $('date').value=isoToday(); $('stress').value=3; $('stressOutput').innerHTML='3 <small>/ 5</small>'; $('formTitle').textContent='Log today'; $('saveButton').innerHTML='Save daily log <span>→</span>'; $('cancelEdit').classList.add('hidden'); }
$('logForm').addEventListener('submit', e=>{ e.preventDefault(); const subjects=$('subjects').value.split(',').map(s=>s.trim()).filter(Boolean); if(!subjects.length)return; const entry={id:editId||crypto.randomUUID(),date:$('date').value,hours:Number($('hours').value),stress:Number($('stress').value),subjects,note:$('note').value.trim()}; logs=editId?logs.map(x=>x.id===editId?entry:x):[...logs,entry]; save(KEYS.logs,logs); resetForm(); render(); });
$('stress').addEventListener('input', e=>$('stressOutput').innerHTML=`${e.target.value} <small>/ 5</small>`);
$('cancelEdit').addEventListener('click',resetForm);
$('historyBody').addEventListener('click',e=>{ const id=e.target.dataset.edit||e.target.dataset.delete;if(!id)return;if(e.target.dataset.delete){if(confirm('Delete this daily log?')){logs=logs.filter(x=>x.id!==id);save(KEYS.logs,logs);render();}}else{const x=logs.find(x=>x.id===id);editId=id;$('date').value=x.date;$('hours').value=x.hours;$('subjects').value=x.subjects.join(', ');$('note').value=x.note;$('stress').value=x.stress;$('stressOutput').innerHTML=`${x.stress} <small>/ 5</small>`;$('formTitle').textContent='Edit daily log';$('saveButton').innerHTML='Update log <span>→</span>';$('cancelEdit').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});}});
$('sortSelect').addEventListener('change',renderHistory);document.querySelectorAll('[data-days]').forEach(btn=>btn.addEventListener('click',()=>{chartDays=Number(btn.dataset.days);document.querySelectorAll('[data-days]').forEach(b=>b.classList.toggle('active',b===btn));$('stressChart').innerHTML=chart('stress');$('hoursChart').innerHTML=chart('hours');}));
$('exportButton').addEventListener('click',()=>{if(!logs.length)return;const rows=[['date','subjects','hours_studied','stress_1_to_5','note'],...sortedLogs().map(x=>[x.date,x.subjects.join('; '),x.hours,x.stress,x.note])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='studyload-logs.csv';a.click();URL.revokeObjectURL(a.href);});
$('insightButton').addEventListener('click',async()=>{const b=$('insightButton'), message=$('aiMessage');b.disabled=true;b.textContent='Analyzing your pattern…';message.className='status';message.textContent='Reading your latest study pattern…';try{const response=await fetch('/api/insight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({logs:sortedLogs().slice(0,14)})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to generate an insight.');insights.unshift({...data,createdAt:new Date().toISOString()});save(KEYS.insights,insights);message.textContent='New insight saved to your history.';render();}catch(err){message.className='status error';message.textContent=err.message;}finally{b.disabled=logs.length<2;b.innerHTML='Analyze recent logs <span>↗</span>';}});
$('date').value=isoToday();$('todayLabel').textContent=new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'}).toUpperCase();render();
